var film = [
  [
    "Studio 1",
    "99 Cahaya",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/99cahaya.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
  [
    "Studio 2",
    "Catatan Si Boy",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/catatansiboy.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
  [
    "Studio 3",
    "Keluarga Cemara 2",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/cemara2.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
  [
    "Studio 4",
    "My Stupid Bos",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/mystupid.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
  [
    "Studio 5",
    "Sang Pemimpi",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/sangpemimpi.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
  [
    "Studio 6",
    "Warkop DKI Reborn",
    "Durasi : 2 : 13 : 00",
    "./lib/assets/warkop.jpg",
    "Genre : Roman",
    "Producer : Mira Lesmana",
    "Cast : Gina S. Noer",
    "Jam Tayang : 10.00",
  ],
];

